### ISSUE TITLE
Could be faster

### ISSUE THREAD

**Issue by millergrnt** [alex-taffe/iOS-Restrictions-Cracker-Linux#1]
its pretty good, but slow as balls, and by slow as balls i mean pretty damn fast just not that fast

**Comment by millergrnt** [comment]
wow okay just close my issues? I see how it is, thanks for actually addressing my issue not just closing it, meanie

**Comment by alex-taffe** [comment]
@millergrnt if you’d read the todo in the readme¯\_(ツ)_/¯
